version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container_2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql